In [2]:
import pandas as pd
import numpy as np

In [3]:
path = ''
df = pd.read_csv(path + 'covid-19-dataset/us-states.csv')

In [4]:
df.head()

         date       state  fips  cases  deaths
0  2020-01-21  Washington    53      1       0
1  2020-01-22  Washington    53      1       0
2  2020-01-23  Washington    53      1       0
3  2020-01-24    Illinois    17      1       0
4  2020-01-24  Washington    53      1       0

In [5]:
df.state.head()

0    Washington
1    Washington
2    Washington
3      Illinois
4    Washington
Name: state, dtype: object

In [6]:
df['date'] = df['date'].astype('datetime64[ns]')

In [7]:
df.sort_values(by = ['date'], inplace = True, ascending = True)

In [8]:
all_dates = df.date.unique()
print(len(all_dates))

128

In [9]:
all_states = df.state.unique()
print(len(all_states))

55

In [12]:
def preprocess(lookup, resolution):
    with open(path + 'covid-19-dataset/processed-data/processed-us-states-' + lookup + '.csv', 'w+') as lookup_file:

        with open(path + 'covid-19-dataset/processed-data/us-states-order.csv', 'w+')  as order_file:

            for date in all_dates:
                filter1 = df[resolution] == 'Georgia'
                filter2 =  df['date'] == date

                if((filter1 & filter2).any()):
                    cases = df.loc[filter1 & filter2]['cases'].to_string(index=False)
                    deaths = df.loc[filter1 & filter2]['deaths'].to_string(index=False)
                else:
                cases = '0'
                deaths = '0'


                print(cases+','+ deaths)
                lookup_file.write(cases+','+ deaths + '\n')

In [13]:
########################### careful here 

lookup = 'cases'
resolution = 'state'

preprocess(lookup= lookup, resolution = resolution)

Washington
 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  5,  5,  5,  5,  7,  10,  17,  23,  32,  47,  75,  86,  110,  141,  179,  279,  338,  419,  511,  609,  675,  794,  908,  1026,  1228,  1404,  1655,  1844,  2101,  2469,  2585,  3208,  3770,  4311,  4896,  5179,  5292,  5588,  6585,  6966,  7498,  7984,  8384,  8682,  9097,  9608,  9887,  10224,  10411,  10538,  10694,  10783,  11152,  11445,  11802,  11805,  12191,  12345,  12539,  12906,  13120,  13484,  13663,  13864,  14059,  14378,  14696,  15010,  15253,  15809,  15905,  16081,  16713,  17017,  17297,  17446,  17592,  17983,  18186,  18287,  18649,  18913,  19109,  19281,  19521,  19746,  19864,  20033,  20274,  20487,  20732,  21005,  21278,  21565

Illinois
0, 0, 0,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  4,  4,  4,  5,  6,  6,  7,  11,  19,  25,  32,  46,  66,  94,  104,  159,  286,  420,  583,  751,  1047,  1285,  1535,  1874,  2538,  3029,  3547,  4613,  5070,  5992,  6978,  7695,  8904,  10357,  11276,  12262,  13549,  15078,  16422,  17887,  19180,  20852,  22025,  23247,  24593,  25734,  27575,  29160,  30357,  31508,  33059,  35108,  36935,  39658,  41777,  43903,  45883,  48102,  50355,  52918,  56055,  58505,  61499,  63840,  65889,  68164,  70802,  73688,  76008,  77662,  79123,  83168,  84874,  88081,  90528,  92669,  94360,  96778,  98298,  100713,  102995,  105710,  108100,  110541,  112248,  113486,  114612

California
0, 0, 0, 0,  1,  2,  2,  2,  2,  2,  3,  3,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  9,  9,  9,  11,  11,  26,  26,  27,  28,  33,  38,  45,  55,  67,  81,  100,  112,  172,  179,  202,  252,  320,  381,  478,  588,  732,  893,  1067,  1283,  1544,  1851,  2240,  2644,  3183,  4060,  4914,  5565,  6266,  7421,  8582,  9816,  11190,  12569,  13796,  15076,  16284,  17540,  19043,  20191,  21366,  22421,  23323,  24334,  25758,  27107,  28142,  29398,  30829,  31544,  33862,  35844,  37573,  39534,  41368,  42590,  43691,  45208,  46570,  48904,  50470,  52318,  53753,  55072,  56333,  58848,  60787,  62481,  64616,  66824,  68051,  69514,  71150,  73218,  74947,  77015,  78933,  80366,  81943,  83981,  86125,  88488,  90801,  92815,  94743,  97017,  99925,  101874

Arizona
0, 0, 0, 0, 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  3,  5,  5,  6,  6,  9,  9,  9,  12,  13,  18,  20,  28,  47,  70,  104,  153,  234,  326,  402,  508,  665,  773,  929,  1169,  1298,  1413,  1600,  1769,  2019,  2269,  2465,  2575,  2726,  3018,  3112,  3393,  3539,  3702,  3806,  3962,  4234,  4507,  4719,  4929,  5064,  5251,  5459,  5769,  6045,  6280,  6526,  6716,  6948,  7202,  7648,  7962,  8364,  8640,  8919,  9305,  9707,  9945,  10526,  10960,  11119,  11380,  11736,  12176,  12674,  13169,  13631,  13937,  14170,  14566,  14897,  15315,  15608,  16040,  16339,  16561,  16783,  17262

Massachusetts
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  3,  8,  13,  28,  41,  92,  95,  108,  123,  138,  164,  197,  218,  256,  328,  413,  525,  646,  777,  1159,  1838,  2417,  3240,  4257,  4955,  5752,  6620,  7738,  8966,  10402,  11736,  12500,  13837,  15202,  16790,  18941,  20974,  22860,  25475,  26867,  28163,  29918,  32181,  34402,  36372,  38077,  39643,  41199,  42944,  46023,  50969,  53348,  54938,  56462,  58302,  60265,  62205,  64311,  66263,  68087,  69087,  70271,  72025,  73721,  75333,  76743,  77793,  78462,  79332,  80497,  82182,  83421,  84933,  86010,  87052,  87925,  88970,  90084,  90889,  91662,  92675,  93271,  93693,  94220

Wisconsin
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  3,  6,  8,  19,  27,  33,  47,  72,  106,  155,  216,  281,  382,  418,  481,  623,  754,  930,  1042,  1120,  1267,  1351,  1550,  1730,  1916,  2112,  2267,  2440,  2578,  2756,  2885,  3068,  3213,  3341,  3428,  3555,  3721,  3875,  4045,  4199,  4346,  4499,  4620,  4845,  5052,  5356,  5687,  5911,  6081,  6289,  6520,  6854,  7314,  7660,  7964,  8236,  8566,  8901,  9215,  9590,  9939,  10219,  10418,  10617,  10903,  11280,  11854,  12368,  12571,  12722,  13001,  13574,  13892,  14557,  14985,  15362,  15646,  15923,  16565

Texas
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  2,  2,  2,  2,  2,  2,  2,  2,  4,  4,  4,  10,  10,  10,  10,  11,  11,  11,  11,  11,  12,  16,  19,  19,  23,  24,  31,  33,  41,  58,  69,  80,  87,  106,  166,  248,  377,  547,  632,  728,  857,  1119,  1542,  1940,  2158,  2709,  3036,  3570,  4255,  4880,  5669,  6566,  7091,  8104,  8968,  9897,  11372,  12290,  13208,  13776,  14487,  15303,  16106,  16928,  18131,  18927,  19441,  20035,  20949,  21769,  22706,  23650,  24494,  25209,  25963,  26868,  27839,  29072,  30342,  31433,  32299,  33134,  34286,  35441,  36682,  37943,  38849,  40037,  40988,  42348,  43822,  45169,  46987,  47866,  48828,  49788,  51080,  52183,  53441,  54369,  55386,  56050,  56490,  57541,  59047

Nebraska
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  10,  10,  10,  11,  11,  11,  11,  12,  13,  13,  13,  13,  13,  13,  13,  13,  13,  13,  14,  14,  16,  16,  17,  23,  24,  27,  29,  31,  33,  36,  43,  47,  53,  61,  62,  73,  77,  84,  91,  99,  121,  136,  185,  193,  249,  273,  296,  339,  376,  437,  490,  538,  594,  678,  718,  805,  870,  930,  994,  1094,  1216,  1348,  1473,  1646,  1726,  1826,  2190,  2474,  2898,  3126,  3487,  3613,  3876,  4332,  4838,  5332,  5686,  6123,  6442,  6771,  7190,  7830,  8233,  8328,  8575,  8732,  9072,  9411,  9766,  10220,  10348,  10625,  10846,  11119,  11424,  11662,  11989,  12134,  12355,  12619,  12976

Utah
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  3,  3,  3,  3,  4,  5,  7,  7,  21,  29,  40,  51,  65,  80,  112,  138,  182,  257,  298,  346,  402,  480,  608,  719,  806,  887,  1012,  1077,  1248,  1426,  1618,  1662,  1737,  1860,  1980,  2103,  2208,  2305,  2368,  2420,  2549,  2687,  2813,  2942,  3071,  3213,  3301,  3451,  3621,  3782,  3950,  4123,  4236,  4343,  4499,  4672,  4829,  4981,  5175,  5326,  5449,  5605,  5724,  5919,  6103,  6251,  6364,  6454,  6624,  6760,  6930,  7068,  7238,  7384,  7530,  7717,  7876,  8057,  8260,  8392,  8521,  8622,  8710

Oregon
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  2,  2,  2,  2,  2,  2,  6,  13,  13,  14,  20,  30,  30,  36,  39,  46,  66,  74,  87,  114,  137,  161,  191,  209,  266,  316,  414,  479,  548,  606,  690,  736,  826,  899,  999,  1068,  1132,  1181,  1239,  1321,  1371,  1447,  1527,  1584,  1633,  1663,  1736,  1785,  1844,  1910,  1956,  2002,  2059,  2127,  2177,  2253,  2311,  2354,  2385,  2446,  2510,  2579,  2635,  2680,  2759,  2839,  2916,  2989,  3068,  3160,  3228,  3286,  3359,  3416,  3479,  3541,  3612,  3623,  3687,  3726,  3801,  3817,  3864,  3888,  3927,  3949,  3967,  4038

Rhode Island
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  2,  2,  2,  2,  3,  3,  3,  3,  5,  5,  5,  20,  20,  20,  21,  23,  33,  44,  44,  66,  83,  106,  124,  132,  165,  203,  239,  294,  408,  488,  566,  657,  711,  806,  922,  1082,  1229,  1450,  1727,  2015,  2349,  2665,  2976,  3251,  3529,  3838,  4177,  4491,  4706,  5090,  5500,  5841,  6256,  6699,  7129,  7439,  7708,  7926,  8247,  8621,  8962,  9289,  9477,  9652,  9933,  10205,  10530,  10779,  10989,  11274,  11450,  11614,  11835,  12016,  12219,  12434,  12674,  12795,  12951,  13356,  13571,  13736,  13952,  14065,  14065,  14210,  14353

New York
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  2,  11,  22,  44,  89,  106,  142,  173,  217,  326,  421,  610,  732,  950,  1375,  2387,  4161,  7113,  10371,  15188,  20899,  25703,  33116,  39057,  44745,  53516,  59783,  67462,  76211,  84363,  92971,  103651,  115963,  124085,  132061,  141703,  151271,  162036,  172830,  182990,  191425,  197973,  205375,  217130,  225761,  233293,  240542,  246741,  251608,  255932,  261591,  267932,  276218,  286901,  292914,  296991,  300276,  304994,  309696,  313575,  318134,  321833,  324357,  326659,  329405,  332931,  335804,  338519,  340657,  342267,  343705,  345828,  348192,  350951,  353136,  355037,  356278,  357757,  359235,  361313,  362991,  364745,  366346,  367625,  368669,  369801

Florida
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  2,  3,  3,  4,  7,  12,  13,  14,  23,  26,  46,  70,  70,  109,  141,  210,  326,  434,  564,  764,  1000,  1222,  1467,  1965,  2477,  3198,  4038,  4942,  5694,  6741,  7765,  9000,  10260,  11537,  12342,  13621,  14739,  15690,  16819,  17960,  18978,  19855,  21011,  21620,  22526,  23332,  24745,  25484,  26306,  27050,  27861,  28301,  29640,  30525,  30831,  31520,  32130,  32838,  33185,  33683,  34720,  35455,  36070,  36889,  37431,  37994,  38820,  39191,  39993,  40588,  40974,  41915,  42394,  43202,  44130,  44803,  45580,  46434,  46936,  47463,  48667,  49443,  50119,  50859,  51738,  52247,  52626

Georgia
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  2,  2,  2,  3,  7,  11,  17,  22,  31,  31,  41,  65,  97,  118,  142,  193,  282,  482,  552,  620,  800,  1095,  1385,  1641,  2198,  2447,  2683,  3032,  4116,  4747,  5444,  5967,  6383,  6742,  7558,  9156,  10204,  10885,  11859,  12261,  12103,  13125,  13913,  14583,  15644,  16658,  17014,  17619,  18447,  19189,  20099,  20905,  21575,  22225,  22459,  23229,  23607,  24300,  25431,  26436,  27268,  27618,  28350,  28876,  29724,  30524,  31089,  31481,  32267,  32448,  33311,  33866,  34422,  35242,  35655,  35954,  36634,  37214,  38162,  38969,  39734,  40408,  40989,  41414,  42066,  42713

New Hampshire
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  2,  2,  2,  2,  4,  4,  4,  5,  5,  6,  7,  7,  13,  17,  26,  39,  44,  55,  65,  78,  101,  108,  137,  158,  187,  214,  258,  314,  367,  415,  479,  540,  621,  669,  715,  747,  788,  819,  885,  929,  985,  1020,  1091,  1139,  1211,  1287,  1342,  1392,  1447,  1491,  1588,  1670,  1720,  1793,  1864,  1938,  2010,  2054,  2146,  2310,  2429,  2518,  2588,  2636,  2741,  2843,  2947,  3011,  3071,  3160,  3239,  3299,  3382,  3464,  3556,  3596,  3652,  3721,  3868,  3935,  4014,  4089,  4149,  4197,  4231,  4286

North Carolina
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  2,  2,  2,  7,  7,  8,  16,  18,  25,  32,  34,  42,  66,  104,  144,  184,  269,  302,  397,  561,  637,  782,  971,  1164,  1302,  1526,  1580,  1857,  2093,  2402,  2585,  2870,  3220,  3423,  3651,  3906,  4310,  4520,  4788,  4992,  5123,  5463,  5859,  6140,  6493,  6764,  6951,  7220,  7608,  8052,  8542,  8830,  9035,  9568,  9947,  10507,  10922,  11514,  11668,  11871,  12283,  12783,  13431,  13879,  14387,  14783,  15069,  15402,  15850,  16593,  17190,  18009,  18537,  19121,  19762,  20221,  20915,  21661,  22731,  23231,  23997,  24188,  24787

New Jersey
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  2,  4,  4,  6,  11,  15,  23,  29,  50,  75,  98,  176,  268,  427,  735,  896,  1336,  1914,  2844,  3675,  4402,  6876,  8825,  11124,  13386,  16636,  18696,  22255,  25590,  29895,  34124,  37505,  41090,  44416,  47437,  51027,  54588,  58151,  61850,  64584,  68824,  71030,  75317,  78467,  81420,  85301,  88806,  92387,  95865,  99989,  102196,  105523,  109038,  111188,  113856,  116264,  118652,  121190,  123717,  126744,  128269,  130593,  131890,  133635,  135454,  137085,  138532,  139945,  140743,  141560,  142704,  143905,  145089,  146334,  148039,  149013,  150399,  151472,  152719,  153104,  154154,  155092,  155764,  156628

Tennessee
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  3,  4,  7,  8,  18,  26,  32,  39,  52,  73,  98,  155,  237,  312,  424,  522,  678,  806,  981,  1180,  1363,  1569,  1721,  2049,  2689,  2868,  3032,  3265,  3538,  3753,  4010,  4246,  4456,  4793,  4983,  5144,  5483,  5654,  5864,  6077,  6423,  6624,  6824,  6994,  7317,  7681,  8169,  8618,  8918,  9435,  9739,  9974,  10255,  10506,  11781,  12376,  12871,  13283,  13555,  13737,  14108,  14276,  14675,  15060,  15423,  15777,  16261,  16588,  16917,  17204,  17391,  17767,  18301,  18534,  18970,  19364,  19765,  20116,  20533,  20960,  21360

Nevada
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  2,  2,  4,  4,  4,  7,  11,  19,  21,  26,  45,  55,  82,  99,  165,  165,  190,  265,  315,  405,  535,  621,  738,  920,  1044,  1113,  1279,  1458,  1549,  1758,  1880,  1971,  2101,  2318,  2456,  2606,  2720,  2860,  3036,  3137,  3212,  3321,  3524,  3626,  3741,  3830,  3937,  4081,  4208,  4398,  4539,  4638,  4708,  4812,  4934,  5053,  5249,  5390,  5473,  5627,  5665,  5744,  5858,  5942,  6046,  6120,  6152,  6311,  6482,  6604,  6733,  6810,  6935,  7059,  7169,  7301,  7402,  7531,  7769,  7886,  7959,  8059,  8150

Maryland
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  3,  3,  3,  5,  6,  9,  13,  13,  18,  27,  32,  39,  57,  85,  108,  150,  195,  245,  290,  349,  423,  581,  775,  1066,  1244,  1414,  1662,  1985,  2331,  2758,  3125,  3609,  4045,  4371,  5529,  6185,  6968,  7694,  8225,  8936,  9472,  10096,  10851,  11641,  12379,  12892,  13750,  14261,  14842,  15805,  16693,  17844,  18664,  19574,  20200,  20942,  21825,  23566,  24568,  25561,  26509,  27217,  28263,  29476,  30592,  31638,  32693,  33483,  34174,  34927,  36021,  37105,  38083,  38920,  39882,  41664,  42442,  43645,  44539,  45608,  46919,  47754,  48290,  49042

Colorado
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  8,  8,  8,  12,  17,  34,  49,  78,  103,  136,  161,  183,  216,  278,  364,  475,  591,  721,  912,  1086,  1432,  1735,  2061,  2315,  2628,  2990,  3346,  3728,  4182,  4574,  4950,  5172,  5429,  5655,  6202,  6510,  6893,  7303,  7691,  7941,  8280,  8675,  9047,  9433,  9730,  10106,  10447,  10878,  11262,  12255,  12967,  13440,  13804,  14239,  14680,  15207,  15661,  16118,  16527,  16799,  17256,  17720,  18264,  18719,  19267,  19595,  19793,  20103,  20442,  20813,  21207,  21604,  21909,  22174,  22454,  22769,  23161,  23456,  23932,  24140,  24256,  24553,  24775

Oklahoma
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  1,  2,  2,  2,  3,  4,  8,  10,  18,  29,  44,  49,  53,  67,  81,  106,  164,  248,  322,  377,  429,  481,  566,  719,  879,  987,  1159,  1251,  1326,  1470,  1523,  1683,  1794,  1868,  1970,  2069,  2184,  2263,  2357,  2465,  2570,  2599,  2680,  2807,  2894,  3017,  3120,  3193,  3253,  3280,  3410,  3473,  3618,  3748,  3851,  3972,  4044,  4127,  4201,  4330,  4424,  4490,  4589,  4613,  4731,  4852,  4962,  5086,  5237,  5310,  5398,  5489,  5532,  5680,  5849,  5960,  6037,  6090,  6137,  6229

Pennsylvania
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  4,  6,  10,  12,  16,  22,  41,  47,  68,  81,  101,  139,  187,  269,  388,  504,  644,  851,  1151,  1690,  2217,  2815,  3441,  4156,  4997,  5805,  7016,  8420,  10109,  11589,  13074,  14582,  16414,  18379,  20128,  21774,  22955,  24295,  25591,  26804,  28314,  30121,  31742,  32992,  34005,  35384,  36763,  38334,  40298,  41626,  42709,  43728,  45323,  46191,  48224,  49764,  51071,  52079,  52992,  53967,  54989,  56149,  57501,  58661,  60037,  60557,  61407,  62194,  63158,  64178,  65228,  65745,  66676,  67404,  68151,  69252,  70305,  71102,  71656,  72356,  72873,  73646

South Carolina
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  2,  6,  7,  9,  10,  12,  13,  19,  28,  33,  47,  60,  81,  126,  172,  194,  299,  342,  424,  456,  539,  660,  774,  925,  1083,  1293,  1554,  1700,  1917,  2049,  2232,  2417,  2552,  2792,  3065,  3207,  3319,  3439,  3553,  3656,  3931,  4086,  4246,  4377,  4439,  4608,  4761,  4917,  5070,  5253,  5490,  5613,  5735,  5881,  6095,  6258,  6489,  6626,  6757,  6841,  6936,  7142,  7367,  7531,  7653,  7792,  7927,  8030,  8189,  8407,  8661,  8816,  8942,  9056,  9175,  9379,  9638,  9895,  10096,  10178,  10416,  10623

Hawaii
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  2,  2,  2,  2,  2,  2,  4,  7,  10,  14,  16,  26,  37,  48,  56,  77,  90,  95,  106,  120,  151,  175,  204,  224,  258,  283,  317,  349,  369,  385,  408,  433,  440,  463,  484,  497,  502,  511,  524,  535,  547,  568,  574,  578,  580,  586,  590,  595,  597,  599,  600,  602,  605,  609,  610,  611,  611,  612,  615,  616,  619,  619,  620,  621,  623,  624,  627,  627,  628,  629,  630,  630,  631,  633,  637,  632,  633,  633,  633,  633,  634

Indiana
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  2,  4,  6,  11,  12,  12,  15,  19,  24,  30,  39,  56,  79,  126,  201,  259,  366,  479,  656,  982,  1232,  1514,  1788,  2159,  2564,  3040,  3439,  3955,  4413,  4956,  5507,  5943,  6351,  6907,  7435,  7928,  8236,  8527,  8955,  9542,  10154,  10641,  11210,  11686,  12097,  12438,  13039,  13680,  14395,  15012,  16137,  16783,  17409,  18099,  18941,  19629,  20267,  20855,  21423,  22286,  22942,  23620,  24239,  24633,  25134,  25676,  26044,  26627,  27281,  27919,  28419,  28897,  29402,  29986,  30673,  31165,  31674,  32151,  32489,  32856,  33242

Kentucky
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  4,  5,  7,  7,  11,  11,  18,  21,  22,  26,  35,  47,  63,  84,  103,  124,  157,  198,  248,  302,  394,  439,  480,  590,  674,  747,  762,  909,  1048,  1057,  1289,  1393,  1525,  1702,  1851,  1963,  2048,  2210,  2295,  2429,  2522,  2707,  2960,  3050,  3193,  3373,  3548,  3779,  3905,  4074,  4146,  4375,  4538,  4708,  4879,  4881,  5223,  5370,  5822,  5946,  6173,  6298,  6469,  6486,  6710,  7003,  7102,  7397,  7578,  7773,  7793,  8041,  8205,  8336,  8475,  8688,  8812,  8842,  8899,  9175,  9313

Minnesota

**Now Time to Verify**

In [119]:
filename = path + 'covid-19-data/processed-data/processed-us-states-' + lookup + '.csv'
verification = np.loadtxt(filename, dtype=int, delimiter=',')

print(verification)

[[   0    0    0 ...  683  696  717]
 [   0    0    0 ... 1479 1577 1696]
 [   0    0    0 ... 1316 1425 1553]
 ...
 [   0    0    0 ...   26   29   31]
 [   0    0    0 ...    2    2    2]
 [   0    0    0 ...    0    0    0]]

In [120]:
flag = False

for i in range(len(verification)):

  if(flag):
    break
    
  state = all_states[i]   
#   print(state)
  for j in range(len(verification[i])):
    if(verification[i][j] != 0):
      date = all_dates[j]

#       print(date)
      
      df_of_state = df[df[resolution]== state]
      df_of_time = df_of_state[df_of_state['date'] == date]
      value = int(df_of_time[lookup].to_string(index=False))
      
      assert value == verification[i][j]
      if( value != verification[i][j]):
        print("Doesn't match", state, date)
        print('verif index: ', j, 'value: ', verification[i][j])
        print('actual: ', value)
        flag = True
        break

In [14]:
states_order = pd.read_csv(path+'covid-19-dataset/processed-data/us-states-order.csv', header=None)
data = pd.read_csv(path+'covid-19-dataset/processed-data/processed-us-states-cases.csv', header=None)

In [15]:
states_order.head()

               0
0     Washington
1       Illinois
2     California
3        Arizona
4  Massachusetts

In [16]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,118,119,120,121,122,123,124,125,126,127
0,1,1,1,1,1,1,1,1,1,1,...,19521,19746,19864,20033,20274,20487,20732,21005,21278,21565
1,0,0,0,1,1,1,1,1,1,2,...,96778,98298,100713,102995,105710,108100,110541,112248,113486,114612
2,0,0,0,0,1,2,2,2,2,2,...,81943,83981,86125,88488,90801,92815,94743,97017,99925,101874
3,0,0,0,0,0,1,1,1,1,1,...,14170,14566,14897,15315,15608,16040,16339,16561,16783,17262
4,0,0,0,0,0,0,0,0,0,0,...,87052,87925,88970,90084,90889,91662,92675,93271,93693,94220

In [17]:
frames = [states_order, data]

In [18]:
result = pd.concat(frames, axis = 1)

In [19]:
result.head()

,0,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
0,Washington,1,1,1,1,1,1,1,1,1,...,19521,19746,19864,20033,20274,20487,20732,21005,21278,21565
1,Illinois,0,0,0,1,1,1,1,1,1,...,96778,98298,100713,102995,105710,108100,110541,112248,113486,114612
2,California,0,0,0,0,1,2,2,2,2,...,81943,83981,86125,88488,90801,92815,94743,97017,99925,101874
3,Arizona,0,0,0,0,0,1,1,1,1,...,14170,14566,14897,15315,15608,16040,16339,16561,16783,17262
4,Massachusetts,0,0,0,0,0,0,0,0,0,...,87052,87925,88970,90084,90889,91662,92675,93271,93693,94220

In [20]:
correct_format = result.T

In [21]:
correct_format.to_csv(path+'covid-19-dataset/processed-data/correct-state-cases.csv', header = False, index = False)

In [23]:
adj = pd.read_csv(path + 'covid-19-dataset/processed-data/us-adj.csv', header=None)

In [24]:
adj.head()

,0,1,2,3,4,5,6,7,8,9
0,Alaska,Alaska,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Alabama,Alabama,Mississippi,Tennessee,Georgia,Florida,NaN,NaN,NaN,NaN
2,Arkansas,Arkansas,Missouri,Tennessee,Mississippi,Louisiana,Texas,Oklahoma,NaN,NaN
3,Arizona,Arizona,California,Nevada,Utah,Colorado,New Mexico,NaN,NaN,NaN
4,California,California,Oregon,Nevada,Arizona,NaN,NaN,NaN,NaN,NaN

In [26]:
states = adj.iloc[:, 0]

In [28]:
states.to_list()

['Alaska',
 'Alabama',
 'Arkansas',
 'Arizona',
 'California',
 'Colorado',
 'Connecticut',
 'DC',
 'Delaware',
 'Florida',
 'Georgia',
 'Hawaii',
 'Iowa',
 'Idaho',
 'Illinois',
 'Indiana',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Maryland',
 'Maine',
 'Michigan',
 'Minnesota',
 'Missouri',
 'Mississippi',
 'Montana',
 'North Carolina',
 'North Dakota',
 'Nebraska',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'Nevada',
 'New York',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Vermont',
 'Washington',
 'Wisconsin',
 'West Virginia',
 'Wyoming']

In [30]:
correct_format = pd.read_csv(path+'covid-19-dataset/processed-data/correct-state-cases.csv')

In [32]:
final_data = correct_format[ states.to_list() ]
final_data

,Alaska,Alabama,Arkansas,Arizona,California,Colorado,Connecticut,DC,Delaware,Florida,...,South Dakota,Tennessee,Texas,Utah,Virginia,Vermont,Washington,Wisconsin,West Virginia,Wyoming
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,409,14149,5775,16040,92815,23932,40022,7966,8690,50119,...,4468,19765,55386,8260,35749,954,20487,14985,1729,813
124,409,14478,5922,16339,94743,24140,40468,8110,8809,50859,...,4563,20116,56050,8392,36244,956,20732,15362,1771,813
125,412,14986,6029,16561,97017,24256,40873,8225,8965,51738,...,4586,20533,56490,8521,37727,962,21005,15646,1782,843
126,416,15650,6180,16783,99925,24553,41303,8334,9066,52247,...,4653,20960,57541,8622,39342,967,21278,15923,1854,850
127,417,16032,6277,17262,101874,24775,41288,8406,9096,52626,...,4710,21360,59047,8710,40249,971,21565,16565,1947,860

In [33]:
final_data.to_csv(path+'covid-19-dataset/processed-data/final-us-state-cases.csv', index=False)

In [34]:
d = final_data
dz = (d-d.mean())/d.std()

In [35]:
dz.to_csv(path+'covid-19-dataset/processed-data/normalized-us-state-cases.csv', index=False)